import os

from dotenv import load_dotenv
from matplotlib.colors import LinearSegmentedColormap

# Import SentenceTransformersClient from its module
from .sentencetransformers_client import SentenceTransformersClient

# --- Configuration ---
# get environment variables
load_dotenv()
SIMILARITY_THRESHOLD = float(os.getenv("SIMILARITY_THRESHOLD", 0.6))
SIMILARITY_METRICS = ["cosine", "euclidean", "manhattan"]


# --- Theme and Keyword Generation ---
def generate_themes_and_keywords() -> list[str]:
    """
    Generates a list of themes and a dictionary of keywords for detecting opening hours.

    Returns:
        tuple: (list of themes, dictionary of keywords for regex)
    """
    lieux = ["bibliothèque", "médiathèque", "mairie", "piscine"]
    jours = ["lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche"]
    actions = ["ouverte", "fermée", "ouverture", "fermeture", "accueil", "horaires"]
    concepts_generaux = [
        "horaires d'ouverture",
        "heures d'ouverture",
        "accueil du public",
        "jour de fermeture",
        "horaires et jours de la semaine",
        "périodes d'ouverture",
        "période scolaire",
        "vacances scolaires",
        "fermeture exceptionnelle",
        "fermeture annuelle",
        "jours fériés",
        "jours spéciaux",
        "horaires spéciaux",
        "quand venir",
        "nous sommes ouverts",
        "nous sommes fermés",
    ]
    expressions_temporelles = [
        "le matin",
        "l'après-midi",
        "de 9h à 12h",
        "de 14h à 18h",
        "de 10h00 à 19h00",
        "9h 12h",
        "14h 18h",
    ]

    # Generate themes by combining actions and days
    themes_jours = [f"{action} le {jour}" for action in actions[:2] for jour in jours]

    # generate themes for each type of place
    themes_lieux = [f"{lieu} {action}" for lieu in lieux for action in actions]

    # Combine all themes into a single list
    base_themes = (
        concepts_generaux + expressions_temporelles + themes_jours + themes_lieux
    )
    base_themes.append("autre")
    return base_themes


# --- Grid Search Parameters ---
GRID_SEARCH_PARAMS = {
    "chunk_size": [20, 50, 100, 250, 500],
    # "chunk_size": [50, 100],
    "chunk_overlap": [0, 10, 25, 50, 100],
    # "chunk_overlap": [0],
    "chunking_strategy": ["langchain", "raw"],
    # "chunking_strategy": ["langchain"],
    "similarity_metric": SIMILARITY_METRICS,
    "themes": {
        "horaires_simple": ["horaires", "autres"],
        "horaires_full": [
            "horaires d'ouverture",
            "heures d'ouverture",
            "accueil du public",
            "jour de fermeture",
            "horaires et jours de la semaine",
            "périodes d'ouverture",
            "période scolaire",
            "vacances scolaires",
            "fermeture exceptionnelle",
            "fermeture annuelle",
            "jours fériés",
            "jours spéciaux",
            "horaires spéciaux",
            "quand venir",
            "nous sommes ouverts",
            "nous sommes fermés",
            "matin",
            "après-midi",
            "soir",
            "matinée",
            "soirée",
            "journée continue",
            "pause déjeuner",
            "pause méridienne",
            "sans interruption",
            "ouverte le lundi",
            "ouverte le mardi",
            "ouverte le mercredi",
            "ouverte le jeudi",
            "ouverte le vendredi",
            "ouverte le samedi",
            "ouverte le dimanche",
            "fermée le lundi",
            "fermée le mardi",
            "fermée le mercredi",
            "fermée le jeudi",
            "fermée le vendredi",
            "fermée le samedi",
            "fermée le dimanche",
            "ouverte le lun",
            "ouverte le mar",
            "ouverte le mer",
            "ouverte le jeu",
            "ouverte le ven",
            "ouverte le sam",
            "ouverte le dim",
            "fermée le lun",
            "fermée le mar",
            "fermée le mer",
            "fermée le jeu",
            "fermée le ven",
            "fermée le sam",
            "fermée le dim",
            "bibliothèque ouverte",
            "bibliothèque fermée",
            "bibliothèque ouverture",
            "bibliothèque fermeture",
            "bibliothèque accueil",
            "bibliothèque horaires",
            "médiathèque ouverte",
            "médiathèque fermée",
            "médiathèque ouverture",
            "médiathèque fermeture",
            "médiathèque accueil",
            "médiathèque horaires",
            "horaires de la bibliothèque",
            "horaires de la médiathèque",
            "heures de consultation",
            "prêt et retour",
            "service public",
            "mairie ouverte",
            "mairie fermée",
            "mairie ouverture",
            "mairie fermeture",
            "mairie accueil",
            "mairie horaires",
            "hôtel de ville",
            "permanence mairie",
            "état civil",
            "services municipaux",
            "accueil mairie",
            "horaires de la mairie",
            "réception du public",
            "piscine ouverte",
            "piscine fermée",
            "piscine ouverture",
            "piscine fermeture",
            "piscine accueil",
            "piscine horaires",
            "bassin ouvert",
            "centre aquatique",
            "horaires de baignade",
            "créneaux libres",
            "nage libre",
            "cours de natation",
            "aquagym",
            "horaires de la piscine",
            "8h00 - 12h00",
            "8h00 - 12h",
            "8h - 12h00",
            "8h - 12h",
            "9h00 - 12h00",
            "9h00 - 12h",
            "9h - 12h00",
            "9h - 12h",
            "10h00 - 12h00",
            "10h00 - 12h",
            "10h - 12h00",
            "10h - 12h",
            "13h00 - 17h00",
            "13h00 - 17h",
            "13h - 17h00",
            "13h - 17h",
            "14h00 - 17h00",
            "14h00 - 17h",
            "14h - 17h00",
            "14h - 17h",
            "13h00 - 18h00",
            "13h00 - 18h",
            "13h - 18h00",
            "13h - 18h",
            "14h00 - 18h00",
            "14h00 - 18h",
            "14h - 18h00",
            "14h - 18h",
            "13h00 - 19h00",
            "13h00 - 19h",
            "13h - 19h00",
            "13h - 19h",
            "14h00 - 19h00",
            "14h00 - 19h",
            "14h - 19h00",
            "14h - 19h",
            "17h00 - 20h00",
            "17h - 20h",
            "18h00 - 21h00",
            "18h - 21h",
            "9h00 - 18h00",
            "9h - 18h",
            "8h30 - 17h30",
            "8h30 - 12h et 14h - 17h30",
            "9h - 12h et 13h30 - 17h",
            "pendant les vacances",
            "hors vacances scolaires",
            "période estivale",
            "saison hivernale",
            "jours ouvrables",
            "jours ouvrés",
            "week-end",
            "samedi matin",
            "dimanche après-midi",
            "actuellement ouvert",
            "actuellement fermé",
            "prochaine ouverture",
            "prochaine fermeture",
            "ouvert aujourd'hui",
            "fermé aujourd'hui",
            "ouvert en continu",
            "fermeture temporaire",
            "de 9h à 12h",
            "de 14h à 17h",
            "entre 9h et 12h",
            "à partir de 9h",
            "jusqu'à 17h",
            "tous les jours sauf",
            "du lundi au vendredi",
            "du mardi au samedi",
            "accès libre",
            "sur rendez-vous",
            "permanence téléphonique",
            "accueil physique",
            "guichet ouvert",
            "service continu",
            "réception ouverte",
            "ouvre ses portes",
            "ferme ses portes",
        ],
        # "horaires_complets": [
        #     "horaires d'ouverture",
        #     "heures d'ouverture",
        #     "accueil du public",
        #     "jour de fermeture",
        #     "horaires et jours de la semaine",
        #     "périodes d'ouverture",
        #     "période scolaire",
        #     "vacances scolaires",
        #     "fermeture exceptionnelle",
        #     "fermeture annuelle",
        #     "jours fériés",
        #     "jours spéciaux",
        #     "horaires spéciaux",
        #     "quand venir",
        #     "nous sommes ouverts",
        #     "nous sommes fermés",
        #     "le matin",
        #     "l'après-midi",
        #     "de 9h à 12h",
        #     "de 14h à 18h",
        #     "de 10h00 à 19h00",
        #     "9h 12h",
        #     "14h 18h",
        #     "ouverte le lundi",
        #     "ouverte le mardi",
        #     "ouverte le mercredi",
        #     "ouverte le jeudi",
        #     "ouverte le vendredi",
        #     "ouverte le samedi",
        #     "ouverte le dimanche",
        #     "fermée le lundi",
        #     "fermée le mardi",
        #     "fermée le mercredi",
        #     "fermée le jeudi",
        #     "fermée le vendredi",
        #     "fermée le samedi",
        #     "fermée le dimanche",
        #     "bibliothèque ouverte",
        #     "bibliothèque fermée",
        #     "bibliothèque ouverture",
        #     "bibliothèque fermeture",
        #     "bibliothèque accueil",
        #     "bibliothèque horaires",
        #     "médiathèque ouverte",
        #     "médiathèque fermée",
        #     "médiathèque ouverture",
        #     "médiathèque fermeture",
        #     "médiathèque accueil",
        #     "médiathèque horaires",
        #     "mairie ouverte",
        #     "mairie fermée",
        #     "mairie ouverture",
        #     "mairie fermeture",
        #     "mairie accueil",
        #     "mairie horaires",
        #     "piscine ouverte",
        #     "piscine fermée",
        #     "piscine ouverture",
        #     "piscine fermeture",
        #     "piscine accueil",
        #     "piscine horaires",
        #     "autres",
        # ],
        # "horaires_medium": [
        #     "horaires",
        #     "horaires et accès",
        #     "horaires d'ouverture",
        #     "heures d'ouverture",
        #     "horaires de la médiathèque",
        #     "horaires de la bibliothèque",
        #     "horaires de la mairie",
        #     "horaires de la piscine",
        #     "fermeture exceptionnelle",
        #     "fermeture temporaire",
        #     "fermeture estivale",
        #     "fermeture annuelle",
        #     "horaires d'été",
        #     "horaires estivaux",
        #     "horaires hors période estivale",
        #     "lundi",
        #     "mardi",
        #     "mercredi",
        #     "jeudi",
        #     "vendredi",
        #     "samedi",
        #     "dimanche",
        #     "matin",
        #     "après-midi",
        #     "soir",
        #     "ouvre ses portes",
        #     "ferme ses portes",
        #     "autres",
        # ],
    },
}

# --- Model Configuration ---
MODELS_TO_TEST = [
    # {
    #     "type": "fastembed",
    #     "name": "BAAI/bge-small-en-v1.5",
    #     "function": FastEmbedClient.get_embeddings,
    # },
    # {
    #     "type": "fastembed",
    #     "name": "BAAI/bge-small-zh-v1.5",
    #     "function": FastEmbedClient.get_embeddings,
    # },
    # {
    #     "type": "fastembed",
    #     "name": "snowflake/snowflake-arctic-embed-xs",
    #     "function": FastEmbedClient.get_embeddings,
    # },
    # {
    #     "type": "fastembed",
    #     "name": "sentence-transformers/all-MiniLM-L6-v2",
    #     "function": FastEmbedClient.get_embeddings,
    # },
    # {
    #     "type": "fastembed",
    #     "name": "jinaai/jina-embeddings-v2-small-en",
    #     "function": FastEmbedClient.get_embeddings,
    # },
    # {
    #     "type": "fastembed",
    #     "name": "snowflake/snowflake-arctic-embed-s",
    #     "function": FastEmbedClient.get_embeddings,
    # },
    # {
    #     "type": "fastembed",
    #     "name": "nomic-ai/nomic-embed-text-v1.5-Q",
    #     "function": FastEmbedClient.get_embeddings,
    # },
    # {
    #     "type": "fastembed",
    #     "name": "BAAI/bge-small-en",
    #     "function": FastEmbedClient.get_embeddings,
    # },
    # {
    #     "type": "fastembed",
    #     "name": "BAAI/bge-base-en-v1.5",
    #     "function": FastEmbedClient.get_embeddings,
    # },
    # {
    #     "type": "fastembed",
    #     "name": "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2",
    #     "function": FastEmbedClient.get_embeddings,
    # },
    # {
    #     "type": "fastembed",
    #     "name": "Qdrant/clip-ViT-B-32-text",
    #     "function": FastEmbedClient.get_embeddings,
    # },
    # {
    #     "type": "fastembed",
    #     "name": "jinaai/jina-embeddings-v2-base-de",
    #     "function": FastEmbedClient.get_embeddings,
    # },
    # {
    #     "type": "fastembed",
    #     "name": "BAAI/bge-base-en",
    #     "function": FastEmbedClient.get_embeddings,
    # },
    # {
    #     "type": "fastembed",
    #     "name": "snowflake/snowflake-arctic-embed-m",
    #     "function": FastEmbedClient.get_embeddings,
    # },
    # {
    #     "type": "fastembed",
    #     "name": "thenlper/gte-base",
    #     "function": FastEmbedClient.get_embeddings,
    # },
    # {
    #     "type": "fastembed",
    #     "name": "jinaai/jina-embeddings-v2-base-en",
    #     "function": FastEmbedClient.get_embeddings,
    # },
    # {
    #     "type": "fastembed",
    #     "name": "nomic-ai/nomic-embed-text-v1.5",
    #     "function": FastEmbedClient.get_embeddings,
    # },
    # {
    #     "type": "fastembed",
    #     "name": "nomic-ai/nomic-embed-text-v1",
    #     "function": FastEmbedClient.get_embeddings,
    # },
    # {
    #     "type": "fastembed",
    #     "name": "snowflake/snowflake-arctic-embed-m-long",
    #     "function": FastEmbedClient.get_embeddings,
    # },
    # {
    #     "type": "fastembed",
    #     "name": "jinaai/jina-clip-v1",
    #     "function": FastEmbedClient.get_embeddings,
    # },
    # {
    #     "type": "fastembed",
    #     "name": "jinaai/jina-embeddings-v2-base-code",
    #     "function": FastEmbedClient.get_embeddings,
    # },
    # {
    #     "type": "fastembed",
    #     "name": "jinaai/jina-embeddings-v2-base-es",
    #     "function": FastEmbedClient.get_embeddings,
    # },
    # {
    #     "type": "fastembed",
    #     "name": "mixedbread-ai/mxbai-embed-large-v1",
    #     "function": FastEmbedClient.get_embeddings,
    # },
    # {
    #     "type": "fastembed",
    #     "name": "jinaai/jina-embeddings-v2-base-zh",
    #     "function": FastEmbedClient.get_embeddings,
    # },
    # {
    #     "type": "fastembed",
    #     "name": "sentence-transformers/paraphrase-multilingual-mpnet-base-v2",
    #     "function": FastEmbedClient.get_embeddings,
    # },
    # {
    #     "type": "fastembed",
    #     "name": "snowflake/snowflake-arctic-embed-l",
    #     "function": FastEmbedClient.get_embeddings,
    # },
    # {
    #     "type": "fastembed",
    #     "name": "BAAI/bge-large-en-v1.5",
    #     "function": FastEmbedClient.get_embeddings,
    # },
    # {
    #     "type": "fastembed",
    #     "name": "thenlper/gte-large",
    #     "function": FastEmbedClient.get_embeddings,
    # },
    # {
    #     "type": "fastembed",
    #     "name": "intfloat/multilingual-e5-large",
    #     "function": FastEmbedClient.get_embeddings,
    # },
    # {
    #     "type": "fastembed",
    #     "name": "jinaai/jina-embeddings-v3",
    #     "function": FastEmbedClient.get_embeddings,
    # },
    # {
    #     "type": "sentence_transformers",
    #     "name": "all-mpnet-base-v2",
    #     "function": SentenceTransformersClient.get_embeddings,
    # },
    # {
    #     "type": "sentence_transformers",
    #     "name": "multi-qa-mpnet-base-dot-v1",
    #     "function": SentenceTransformersClient.get_embeddings,
    # },
    # {
    #     "type": "sentence_transformers",
    #     "name": "all-distilroberta-v1",
    #     "function": SentenceTransformersClient.get_embeddings,
    # },
    # {
    #     "type": "sentence_transformers",
    #     "name": "all-MiniLM-L12-v2",
    #     "function": SentenceTransformersClient.get_embeddings,
    # },
    # {
    #     "type": "sentence_transformers",
    #     "name": "multi-qa-distilbert-cos-v1",
    #     "function": SentenceTransformersClient.get_embeddings,
    # },
    # {
    #     "type": "sentence_transformers",
    #     "name": "all-MiniLM-L6-v2",
    #     "function": SentenceTransformersClient.get_embeddings,
    # },
    # {
    #     "type": "sentence_transformers",
    #     "name": "multi-qa-MiniLM-L6-cos-v1",
    #     "function": SentenceTransformersClient.get_embeddings,
    # },
    {
        "type": "sentence_transformers",
        "name": "paraphrase-multilingual-mpnet-base-v2",
        "function": SentenceTransformersClient.get_embeddings,
    },
    # {
    #     "type": "sentence_transformers",
    #     "name": "paraphrase-albert-small-v2",
    #     "function": SentenceTransformersClient.get_embeddings,
    # },
    {
        "type": "sentence_transformers",
        "name": "paraphrase-multilingual-MiniLM-L12-v2",
        "function": SentenceTransformersClient.get_embeddings,
    },
    # {
    #     "type": "sentence_transformers",
    #     "name": "paraphrase-MiniLM-L3-v2",
    #     "function": SentenceTransformersClient.get_embeddings,
    # },
    {
        "type": "sentence_transformers",
        "name": "distiluse-base-multilingual-cased-v1",
        "function": SentenceTransformersClient.get_embeddings,
    },
    {
        "type": "sentence_transformers",
        "name": "distiluse-base-multilingual-cased-v2",
        "function": SentenceTransformersClient.get_embeddings,
    },
    {
        "type": "api",
        "name": "nomic-embed-text",
        "base_url": "https://api.erasme.homes/v1",
        "function": lambda client: client.get_embeddings,
    },
    # {
    #     "type": "api",
    #     "name": "mistral-embed",
    #     "base_url": "https://api.mistral.ai/v1",
    #     "function": lambda client: client.get_embeddings,
    # },
    # {
    #     "type": "api",
    #     "name": "voyage-3-large",
    #     "base_url": "https://api.voyageai.com/v1",
    #     "function": lambda client: client.get_embeddings,
    # },
]

# --- Output Configuration ---
# Sets the output directory in the same folder as the script
SCRIPT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT_DIR = os.path.join(SCRIPT_DIR, "data", "heatmaps")
os.makedirs(OUTPUT_DIR, exist_ok=True)

# --- Colormap for Heatmaps ---
CMAP = LinearSegmentedColormap.from_list(
    "custom",
    ["#2b83ba", "#abdda4", "#ffffbf", "#fdae61", "#d7191c"],
)
